apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-kalkulator
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  team: k9saksbehandling
  liveness:
    path: /isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 20
    timeout: 1
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  ingresses:
    - "https://app-q1.adeo.no/omsorgspenger-kalkulator"
    - "https://omsorgspenger-kalkulator.nais.preprod.local/"
