name: Valider pull request
on: [pull_request]
jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
      - name: Sette opp Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Installere dependencies
        run: yarn install --ignore-optional --no-progress --frozen-lockfile
      - name: Bygge dist
        run: yarn build
      - name: Tester og linting
        run: yarn test --watchAll=false


